export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const DEPARTMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_DEPARTMENTS_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID!;
export const STAFF_ID = process.env.NEXT_PUBLIC_APPWRITE_STAFF_ID!;
export const PATIENT_ID = process.env.NEXT_PUBLIC_APPWRITE_PATIENT_ID!;